services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: electroscan
      POSTGRES_PASSWORD: electroscan123
      POSTGRES_DB: electroscan
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electroscan"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://electroscan:electroscan123@db:5432/electroscan
      JWT_SECRET_KEY: dev_secret_key_cambiar_en_produccion
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 30
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: qwen3.5:9b
      FOTO_STORAGE: local
      FOTO_LOCAL_PATH: ./uploads
    depends_on:
      db:
        condition: service_healthy
